### ISSUE TITLE
1.2.0 does not build with the new Appcelerator Studio

### ISSUE THREAD

**Issue by alexlarocca** [mpociot/titanium-mobile-zip-module#7]
[TRACE] :  Undefined symbols for architecture x86_64:
[TRACE] :    "_OBJC_CLASS_$_Zip", referenced from:
[TRACE] :        objc-class-ref in libde.marcelpociot.zip.a(DeMarcelpociotZipModule.o)
[TRACE] :       (maybe you meant: _OBJC_CLASS_$_ZipArchive)
[TRACE] :  ld: symbol(s) not found for architecture x86_64
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[TRACE] :  Ld build/Niki\ Agenda.build/Debug-iphonesimulator/Niki\ Agenda-iPad.build/Objects-normal/i386/Niki\ Agenda normal i386
[TRACE] :      cd "/Users/alessandro/Documents/Titanium Studio Workspace/Niki Agenda/build/iphone"
[TRACE] :      export IPHONEOS_DEPLOYMENT_TARGET=7.0
[TRACE] :      export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/bin:/Users/alessandro/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin"
[TRACE] :      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/alessandro/Documents/Titanium\ Studio\ Workspace/Niki\ Agenda/build/iphone/build/Debug-iphonesimulator -L/Users/alessandro/Documents/Titanium\ Studio\ Workspace/Niki\ Agenda/build/iphone/lib -L/Users/alessandro/Library/Application\ Support/Titanium/modules/iphone/bencoding.utterance/0.4 -L/Users/alessandro/Library/Application\ Support/Titanium/modules/iphone/ti.compression/1.1.1 -L/Users/alessandro/Library/Application\ Support/Titanium/modules/iphone/com.0x82.dropbox/3.0 -L/Users/alessandro/Library/Application\ Support/Titanium/modules/iphone/de.marcelpociot.zip/1.2.0 -L/Users/alessandro/Documents/Titanium\ Studio\ Workspace/Niki\ Agenda/build/iphone/Classes/APSAnalytics -L/Users/alessandro/Documents/Titanium\ Studio\ Workspace/Niki\ Agenda/build/iphone/Classes/APSHTTPClient -F/Users/alessandro/Documents/Titanium\ Studio\ Workspace/Niki\ Agenda/build/iphone/build/Debug-iphonesimulator -filelist /Users/alessandro/Documents/Titanium\ Studio\ Workspace/Niki\ Agenda/build/iphone/build/Niki\ Agenda.build/Debug-iphonesimulator/Niki\ Agenda-iPad.build/Objects-normal/i386/Niki\ Agenda.LinkFileList -dead_strip -Xlinker -objc_abi_version -Xlinker 2 -ObjC -weak-lti_ios_profiler -weak-lti_ios_debugger -weak-lTiCore -fobjc-link-runtime -Xlinker -no_implicit_dylibs -stdlib=libc++ -mios-simulator-version-min=7.0 -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/alessandro/Documents/Titanium\ Studio\ Workspace/Niki\ Agenda/build/iphone/build/Niki\ Agenda.build/Debug-iphonesimulator/Niki\ Agenda-iPad.build/Niki\ Agenda.app.xcent -weak_framework iAd -framework CoreMedia -weak_framework CoreMotion -lAPSAnalytics -weak_framework CoreText -framework EventKit -framework EventKitUI -weak_framework Security -framework Foundation -weak_framework UIKit -framework CoreGraphics -framework AddressBook -framework AddressBookUI -framework CFNetwork -framework CoreLocation -weak_framework MapKit -framework MessageUI -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -lsqlite3 -lz -framework AudioToolbox -weak_framework MediaPlayer -lAPSHTTPClient -framework AVFoundation -lxml2 -framework StoreKit -ltiverify -lbencoding.utterance -lti.compression -lcom.0x82.dropbox -lde.marcelpociot.zip -licucore -Xlinker -dependency_info -Xlinker /Users/alessandro/Documents/Titanium\ Studio\ Workspace/Niki\ Agenda/build/iphone/build/Niki\ Agenda.build/Debug-iphonesimulator/Niki\ Agenda-iPad.build/Objects-normal/i386/Niki\ Agenda_dependency_info.dat -o /Users/alessandro/Documents/Titanium\ Studio\ Workspace/Niki\ Agenda/build/iphone/build/Niki\ Agenda.build/Debug-iphonesimulator/Niki\ Agenda-iPad.build/Objects-normal/i386/Niki\ Agenda
[TRACE] :  Undefined symbols for architecture i386:
[TRACE] :    "_OBJC_CLASS_$_Zip", referenced from:
[TRACE] :        objc-class-ref in libde.marcelpociot.zip.a(DeMarcelpociotZipModule.o)
[TRACE] :       (maybe you meant: _OBJC_CLASS_$_ZipArchive
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Niki\ Agenda.build/Debug-iphonesimulator/Niki\ Agenda-iPad.build/Objects-normal/x86_64/Niki\ Agenda normal x86_64
[ERROR] :  (1 failure)
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/alessandro/.appcelerator/install/0.2.282/package/node_modules/appc-cli-titanium/plugins/run.js:84:66)
    at ChildProcess.emit (events.js:117:20)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)

**Comment by moizchhatriwala** [comment]
I got success, I re write some of the code and replaced the outdated library to get this module worked properly.
